/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_auth-layout/route'
import { Route as homeHomeLayoutRouteImport } from './routes/(home)/_home-layout/route'
import { Route as homeHomeLayoutIndexImport } from './routes/(home)/_home-layout/index'
import { Route as AuthLayoutSignUpSplatImport } from './routes/_auth-layout/sign-up.$'
import { Route as AuthLayoutSignInSplatImport } from './routes/_auth-layout/sign-in.$'
import { Route as homeHomeLayoutPlaylistsImport } from './routes/(home)/_home-layout/playlists'

// Create Virtual Routes

const homeImport = createFileRoute('/(home)')()

// Create/Update Routes

const homeRoute = homeImport.update({
  id: '/(home)',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRouteRoute = AuthLayoutRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRoute,
} as any)

const homeHomeLayoutRouteRoute = homeHomeLayoutRouteImport.update({
  id: '/_home-layout',
  getParentRoute: () => homeRoute,
} as any)

const homeHomeLayoutIndexRoute = homeHomeLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeHomeLayoutRouteRoute,
} as any)

const AuthLayoutSignUpSplatRoute = AuthLayoutSignUpSplatImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

const AuthLayoutSignInSplatRoute = AuthLayoutSignInSplatImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

const homeHomeLayoutPlaylistsRoute = homeHomeLayoutPlaylistsImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => homeHomeLayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/(home)': {
      id: '/(home)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeImport
      parentRoute: typeof rootRoute
    }
    '/(home)/_home-layout': {
      id: '/(home)/_home-layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeHomeLayoutRouteImport
      parentRoute: typeof homeRoute
    }
    '/(home)/_home-layout/playlists': {
      id: '/(home)/_home-layout/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof homeHomeLayoutPlaylistsImport
      parentRoute: typeof homeHomeLayoutRouteImport
    }
    '/_auth-layout/sign-in/$': {
      id: '/_auth-layout/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthLayoutSignInSplatImport
      parentRoute: typeof AuthLayoutRouteImport
    }
    '/_auth-layout/sign-up/$': {
      id: '/_auth-layout/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthLayoutSignUpSplatImport
      parentRoute: typeof AuthLayoutRouteImport
    }
    '/(home)/_home-layout/': {
      id: '/(home)/_home-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeHomeLayoutIndexImport
      parentRoute: typeof homeHomeLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteRouteChildren {
  AuthLayoutSignInSplatRoute: typeof AuthLayoutSignInSplatRoute
  AuthLayoutSignUpSplatRoute: typeof AuthLayoutSignUpSplatRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutSignInSplatRoute: AuthLayoutSignInSplatRoute,
  AuthLayoutSignUpSplatRoute: AuthLayoutSignUpSplatRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

interface homeHomeLayoutRouteRouteChildren {
  homeHomeLayoutPlaylistsRoute: typeof homeHomeLayoutPlaylistsRoute
  homeHomeLayoutIndexRoute: typeof homeHomeLayoutIndexRoute
}

const homeHomeLayoutRouteRouteChildren: homeHomeLayoutRouteRouteChildren = {
  homeHomeLayoutPlaylistsRoute: homeHomeLayoutPlaylistsRoute,
  homeHomeLayoutIndexRoute: homeHomeLayoutIndexRoute,
}

const homeHomeLayoutRouteRouteWithChildren =
  homeHomeLayoutRouteRoute._addFileChildren(homeHomeLayoutRouteRouteChildren)

interface homeRouteChildren {
  homeHomeLayoutRouteRoute: typeof homeHomeLayoutRouteRouteWithChildren
}

const homeRouteChildren: homeRouteChildren = {
  homeHomeLayoutRouteRoute: homeHomeLayoutRouteRouteWithChildren,
}

const homeRouteWithChildren = homeRoute._addFileChildren(homeRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthLayoutRouteRouteWithChildren
  '/': typeof homeHomeLayoutIndexRoute
  '/playlists': typeof homeHomeLayoutPlaylistsRoute
  '/sign-in/$': typeof AuthLayoutSignInSplatRoute
  '/sign-up/$': typeof AuthLayoutSignUpSplatRoute
}

export interface FileRoutesByTo {
  '': typeof AuthLayoutRouteRouteWithChildren
  '/playlists': typeof homeHomeLayoutPlaylistsRoute
  '/sign-in/$': typeof AuthLayoutSignInSplatRoute
  '/sign-up/$': typeof AuthLayoutSignUpSplatRoute
  '/': typeof homeHomeLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth-layout': typeof AuthLayoutRouteRouteWithChildren
  '/(home)': typeof homeRouteWithChildren
  '/(home)/_home-layout': typeof homeHomeLayoutRouteRouteWithChildren
  '/(home)/_home-layout/playlists': typeof homeHomeLayoutPlaylistsRoute
  '/_auth-layout/sign-in/$': typeof AuthLayoutSignInSplatRoute
  '/_auth-layout/sign-up/$': typeof AuthLayoutSignUpSplatRoute
  '/(home)/_home-layout/': typeof homeHomeLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/playlists' | '/sign-in/$' | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/playlists' | '/sign-in/$' | '/sign-up/$' | '/'
  id:
    | '__root__'
    | '/_auth-layout'
    | '/(home)'
    | '/(home)/_home-layout'
    | '/(home)/_home-layout/playlists'
    | '/_auth-layout/sign-in/$'
    | '/_auth-layout/sign-up/$'
    | '/(home)/_home-layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  homeRoute: typeof homeRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  homeRoute: homeRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth-layout",
        "/(home)"
      ]
    },
    "/_auth-layout": {
      "filePath": "_auth-layout/route.tsx",
      "children": [
        "/_auth-layout/sign-in/$",
        "/_auth-layout/sign-up/$"
      ]
    },
    "/(home)": {
      "filePath": "(home)/_home-layout",
      "children": [
        "/(home)/_home-layout"
      ]
    },
    "/(home)/_home-layout": {
      "filePath": "(home)/_home-layout/route.tsx",
      "parent": "/(home)",
      "children": [
        "/(home)/_home-layout/playlists",
        "/(home)/_home-layout/"
      ]
    },
    "/(home)/_home-layout/playlists": {
      "filePath": "(home)/_home-layout/playlists.tsx",
      "parent": "/(home)/_home-layout"
    },
    "/_auth-layout/sign-in/$": {
      "filePath": "_auth-layout/sign-in.$.tsx",
      "parent": "/_auth-layout"
    },
    "/_auth-layout/sign-up/$": {
      "filePath": "_auth-layout/sign-up.$.tsx",
      "parent": "/_auth-layout"
    },
    "/(home)/_home-layout/": {
      "filePath": "(home)/_home-layout/index.tsx",
      "parent": "/(home)/_home-layout"
    }
  }
}
ROUTE_MANIFEST_END */
